// Kernel symbol table — generated by scripts/generate_syms.zig at build time
// and linked into the `_symbols` section. ksym_name_from_addr lets the trace
// system print the name of the function that was hooked.

const PL: i32 = 1;

extern fn trace_output(interface: i32, str: [*:0]const u8) void;
extern fn trace_output_u64(interface: i32, in: u64) void;

extern var ksyms: u64;

const KernelSymbol = extern struct {
    address: u64,
    name: [56]u8,
};

fn ksTable() [*]KernelSymbol {
    return @ptrCast(&ksyms);
}

var ksyms_count: u64 = 0;

/// Linear scan for the symbol whose address matches `addr`.
export fn ksym_name_from_addr(addr: u64) ?[*:0]const u8 {
    const table = ksTable();
    var i: usize = 0;
    while (i < ksyms_count) : (i += 1) {
        if (table[i].address == addr) {
            return @ptrCast(&table[i].name[0]);
        }
    }
    return null;
}

/// Walk the table until the sentinel (zero-name) entry to find the count.
export fn cal_ksyms_count() void {
    const table = ksTable();
    var count: u64 = 0;
    var i: usize = 0;
    while (table[i].name[0] != 0) : (i += 1) {
        count += 1;
    }
    ksyms_count = count;
}

export fn ksyms_init() void {
    const table = ksTable();

    cal_ksyms_count();
    trace_output(PL, "found ");
    trace_output_u64(PL, ksyms_count);
    trace_output(PL, " kernel symbols\n");

    var i: usize = 0;
    while (i < ksyms_count) : (i += 1) {
        trace_output_u64(PL, table[i].address);
        trace_output(PL, " ");
        trace_output(PL, @ptrCast(&table[i].name[0]));
        trace_output(PL, "\n");
    }
}
