//! The assembly-visible half of the ABI records.
//!
//! Three numbers the `.S` files consume by raw value are not arch constants —
//! they are *layout facts* owned by Rust records:
//!
//!   * `S_FRAME_SIZE`        = `size_of::<KeRegs>()`   — entry.S reserves it
//!   * `NR_SYSCALLS`         = the dispatch cap        — entry.S caps `b.hs` on it
//!   * `CORE_CONTEXT_OFFSET` = `offset_of!(TaskStruct, core_context)` — sched.S
//!
//! `S_FRAME_SIZE` and `CORE_CONTEXT_OFFSET` come from `flashos-abi` (the
//! kernel-private `crates/abi`); `NR_SYSCALLS` from the public
//! `flashsdk-abi::syscall`. This module renders all three into
//! `rust-out/asm_defs_abi.inc`, which `arch/aarch64/asm_defs_common.inc`
//! `#include`s — so the assembly reads the live value instead of a hand-copied
//! literal, and a field appended in the wrong place moves the number on both
//! sides at once.
//!
//! The kernel/canary build regenerates the include before assembling and puts
//! `rust-out` on the assembler include path. `--check` guards the other
//! direction: that nobody has re-introduced a hand-written copy of these facts
//! in `asm_defs_common.inc`, which would silently re-open the drift the include
//! closed.

use std::fmt::Write as _;
use std::path::Path;

use flashos_abi::task::{KeRegs, TaskStruct};
use flashsdk_abi::syscall::NR_SYSCALLS;

/// The include that pulls the generated facts into the assembly.
const REFERENCE_INC: &str = "arch/aarch64/asm_defs_common.inc";

/// The `#include` line `asm_defs_common.inc` must carry so the generated facts
/// reach the assembler.
const GENERATED_INCLUDE: &str = "#include \"asm_defs_abi.inc\"";

/// A fact assembly consumes by raw number, and where Rust computes it from.
struct Fact {
    name: &'static str,
    value: u64,
    derivation: &'static str,
}

fn facts() -> Vec<Fact> {
    vec![
        Fact {
            name: "S_FRAME_SIZE",
            value: std::mem::size_of::<KeRegs>() as u64,
            derivation: "size_of::<KeRegs>()",
        },
        Fact {
            name: "NR_SYSCALLS",
            value: NR_SYSCALLS as u64,
            derivation: "syscall::NR_SYSCALLS",
        },
        Fact {
            name: "CORE_CONTEXT_OFFSET",
            value: std::mem::offset_of!(TaskStruct, core_context) as u64,
            derivation: "offset_of!(TaskStruct, core_context)",
        },
    ]
}

fn render() -> String {
    let mut s = String::new();
    s.push_str(
        "/*\n * Generated by `cargo xtask asm-defs` — do not edit.\n *\n \
         * Assembly-visible layout facts, derived from the ABI records.\n \
         * arch/aarch64/asm_defs_common.inc #includes this file, and the\n \
         * kernel/canary build regenerates it before assembling.\n */\n\n\
         #ifndef ASM_DEFS_ABI_INC\n#define ASM_DEFS_ABI_INC\n\n",
    );
    for f in facts() {
        let _ = writeln!(s, "/* {} */", f.derivation);
        let _ = writeln!(s, "#define {:<20} {}\n", f.name, f.value);
    }
    s.push_str("#endif /* ASM_DEFS_ABI_INC */\n");
    s
}

/// Pull `#define NAME <int>` out of the reference include. Only the plain
/// integer forms are read — the composed expressions (TCR_EL1_VAL and friends)
/// are arch constants Rust does not own and has no business re-deriving.
fn literal(inc: &str, name: &str) -> Option<u64> {
    for line in inc.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix("#define ") else {
            continue;
        };
        let Some(rest) = rest.trim_start().strip_prefix(name) else {
            continue;
        };
        if !rest.starts_with(char::is_whitespace) {
            continue; // a longer name that merely starts with `name`
        }
        let val = rest.split("/*").next().unwrap_or("").trim();
        return val.parse::<u64>().ok();
    }
    None
}

/// Audit the reference include: the generated facts must reach the assembler
/// through the `#include`, and none of them may be hand-`#define`d again — a
/// re-added literal is a drift-prone copy of a number Rust owns. Returns one
/// line per problem; an empty vec means the include is wired correctly.
fn audit(inc: &str) -> Vec<String> {
    let mut bad = Vec::new();
    if !inc.contains(GENERATED_INCLUDE) {
        bad.push(format!(
            "  {REFERENCE_INC} does not `{GENERATED_INCLUDE}` — the generated \
             facts never reach the assembler"
        ));
    }
    for f in facts() {
        if literal(inc, f.name).is_some() {
            bad.push(format!(
                "  {} is hand-#defined in {REFERENCE_INC}; it must come from the \
                 generated include ({}), not a copy",
                f.name, f.derivation
            ));
        }
    }
    bad
}

/// Write the generated include, and (when `check`) prove the reference include
/// still consumes it without re-copying any fact.
pub fn run(root: &Path, check: bool) -> Result<(), String> {
    let out_dir = root.join("rust-out");
    std::fs::create_dir_all(&out_dir).map_err(|e| format!("mkdir rust-out: {e}"))?;
    let out = out_dir.join("asm_defs_abi.inc");
    std::fs::write(&out, render()).map_err(|e| format!("write {}: {e}", out.display()))?;
    println!("wrote {}", out.display());

    if !check {
        return Ok(());
    }

    let inc_path = root.join(REFERENCE_INC);
    let inc = std::fs::read_to_string(&inc_path)
        .map_err(|e| format!("read {}: {e}", inc_path.display()))?;

    let bad = audit(&inc);

    if !bad.is_empty() {
        return Err(format!(
            "the assembly-visible ABI facts are no longer single-sourced ({} \
             problem(s)):\n{}\n\n\
             The .S files must read these numbers from the generated \
             rust-out/asm_defs_abi.inc, not a hand-written literal — a copy here \
             corrupts exception entry and context switching silently when it rots.",
            bad.len(),
            bad.join("\n")
        ));
    }

    println!("asm-defs OK: {REFERENCE_INC} consumes the generated facts, no copies");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reads_a_plain_define() {
        let inc = "#define S_FRAME_SIZE            272\n";
        assert_eq!(literal(inc, "S_FRAME_SIZE"), Some(272));
    }

    /// `PAGE_SHIFT` must not answer a lookup for `PAGE_S` — a prefix match would
    /// silently flag the wrong constant as a re-added copy.
    #[test]
    fn does_not_prefix_match_a_longer_name() {
        let inc = "#define PAGE_SHIFT          12\n";
        assert_eq!(literal(inc, "PAGE_SH"), None);
    }

    /// Composed expressions are arch constants, not Rust-owned layout facts. The
    /// parser must decline them rather than guess.
    #[test]
    fn declines_a_composed_expression() {
        let inc = "#define PAGE_SIZE           (1 << PAGE_SHIFT)\n";
        assert_eq!(literal(inc, "PAGE_SIZE"), None);
    }

    /// The clean state: the include wires in the generated file and hand-defines
    /// none of the three facts.
    #[test]
    fn a_wired_include_with_no_copies_passes() {
        let inc = "\
#define PAGE_SHIFT          12
#include \"asm_defs_abi.inc\"

#endif /* ASM_DEFS_COMMON_INC */
";
        assert!(audit(inc).is_empty(), "{:?}", audit(inc));
    }

    /// The regression this guard exists for: someone re-adds a hand literal,
    /// re-opening the drift the include closed.
    #[test]
    fn a_re_added_hand_literal_is_caught() {
        let inc = "\
#include \"asm_defs_abi.inc\"
#define NR_SYSCALLS  56
";
        let bad = audit(inc);
        assert_eq!(bad.len(), 1, "expected one problem: {bad:?}");
        assert!(bad[0].contains("NR_SYSCALLS"));
        assert!(bad[0].contains("hand-#defined"));
    }

    /// The other way to break the wiring: drop the `#include`, so the generated
    /// facts never reach the assembler.
    #[test]
    fn a_missing_include_is_caught() {
        let inc = "#define PAGE_SHIFT          12\n";
        let bad = audit(inc);
        assert_eq!(bad.len(), 1, "expected one problem: {bad:?}");
        assert!(bad[0].contains("does not"));
    }

    /// The live include must pass — this is the gate in its green state.
    #[test]
    fn the_real_include_is_wired_and_copy_free() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
        let inc = std::fs::read_to_string(root.join(REFERENCE_INC)).unwrap();
        assert!(
            audit(&inc).is_empty(),
            "arch/aarch64/asm_defs_common.inc is not single-sourced: {:?}",
            audit(&inc)
        );
    }

    /// The generated include must carry every fact, and each must be the value
    /// the record actually has — not a copy that can rot.
    #[test]
    fn rendered_include_carries_the_live_values() {
        let s = render();
        for f in facts() {
            assert!(
                s.contains(&format!("#define {:<20} {}", f.name, f.value)),
                "generated include is missing {}",
                f.name
            );
        }
    }
}
