//! The assembly-visible half of the ABI crate.
//!
//! Three numbers in `arch/aarch64/asm_defs_common.inc` are not arch constants —
//! they are *layout facts* the .S files hardcode about Rust/Flash records:
//!
//!   * `S_FRAME_SIZE`        = `size_of::<KeRegs>()`   — entry.S reserves it
//!   * `NR_SYSCALLS`         = the dispatch cap        — entry.S caps `b.hs` on it
//!   * `CORE_CONTEXT_OFFSET` = `offset_of!(TaskStruct, core_context)` — sched.S
//!
//! Nothing checks that the assembly's literals still agree with the records; the
//! Flash side pins only `S_FRAME_SIZE` by comment and a comptime assert. This
//! module derives all three from `flashos-abi` and diffs them against the
//! include, so a field appended in the wrong place fails the build instead of
//! corrupting the next context switch.
//!
//! The generated include is written but not yet consumed: no `.S` file has been
//! switched onto it, so assembly behaviour is unchanged. Today its job is only to
//! prove that the two sides already agree.

use std::fmt::Write as _;
use std::path::Path;

use flashos_abi::task::{KeRegs, TaskStruct};
use flashsdk_abi::syscall::NR_SYSCALLS;

/// The one include the .S files read the three facts from today.
const REFERENCE_INC: &str = "arch/aarch64/asm_defs_common.inc";

/// A fact assembly consumes by raw number, and where Rust computes it from.
struct Fact {
    name: &'static str,
    value: u64,
    derivation: &'static str,
}

fn facts() -> Vec<Fact> {
    vec![
        Fact {
            name: "S_FRAME_SIZE",
            value: std::mem::size_of::<KeRegs>() as u64,
            derivation: "size_of::<KeRegs>()",
        },
        Fact {
            name: "NR_SYSCALLS",
            value: NR_SYSCALLS as u64,
            derivation: "syscall::NR_SYSCALLS",
        },
        Fact {
            name: "CORE_CONTEXT_OFFSET",
            value: std::mem::offset_of!(TaskStruct, core_context) as u64,
            derivation: "offset_of!(TaskStruct, core_context)",
        },
    ]
}

fn render() -> String {
    let mut s = String::new();
    s.push_str(
        "/*\n * Generated by `cargo xtask asm-defs` — do not edit.\n *\n \
         * Assembly-visible layout facts, derived from crates/abi. `cargo xtask\n \
         * asm-defs --check` diffs these against the hand-written literals in\n \
         * arch/aarch64/asm_defs_common.inc, which the .S files consume today.\n */\n\n\
         #ifndef ASM_DEFS_ABI_INC\n#define ASM_DEFS_ABI_INC\n\n",
    );
    for f in facts() {
        let _ = writeln!(s, "/* {} */", f.derivation);
        let _ = writeln!(s, "#define {:<20} {}\n", f.name, f.value);
    }
    s.push_str("#endif /* ASM_DEFS_ABI_INC */\n");
    s
}

/// Pull `#define NAME <int>` out of the reference include. Only the plain
/// integer forms are read — the composed expressions (TCR_EL1_VAL and friends)
/// are arch constants Rust does not own and has no business re-deriving.
fn literal(inc: &str, name: &str) -> Option<u64> {
    for line in inc.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix("#define ") else {
            continue;
        };
        let Some(rest) = rest.trim_start().strip_prefix(name) else {
            continue;
        };
        if !rest.starts_with(char::is_whitespace) {
            continue; // a longer name that merely starts with `name`
        }
        let val = rest.split("/*").next().unwrap_or("").trim();
        return val.parse::<u64>().ok();
    }
    None
}

/// Diff every fact against the include's literals. Returns one line per
/// disagreement; an empty vec means the assembly and the ABI crate agree.
fn compare(inc: &str, verbose: bool) -> Vec<String> {
    let mut bad = Vec::new();
    for f in facts() {
        match literal(inc, f.name) {
            Some(asm) if asm == f.value => {
                if verbose {
                    println!("  {:<20} {} == {}", f.name, f.value, f.derivation);
                }
            }
            Some(asm) => bad.push(format!(
                "  {}: assembly says {asm}, {} says {}",
                f.name, f.derivation, f.value
            )),
            None => bad.push(format!(
                "  {}: not found as a plain #define in {REFERENCE_INC}",
                f.name
            )),
        }
    }
    bad
}

/// Write the generated include, and (when `check`) prove the assembly's literals
/// still match. Returns the path written.
pub fn run(root: &Path, check: bool) -> Result<(), String> {
    let out_dir = root.join("rust-out");
    std::fs::create_dir_all(&out_dir).map_err(|e| format!("mkdir rust-out: {e}"))?;
    let out = out_dir.join("asm_defs_abi.inc");
    std::fs::write(&out, render()).map_err(|e| format!("write {}: {e}", out.display()))?;
    println!("wrote {}", out.display());

    if !check {
        return Ok(());
    }

    let inc_path = root.join(REFERENCE_INC);
    let inc = std::fs::read_to_string(&inc_path)
        .map_err(|e| format!("read {}: {e}", inc_path.display()))?;

    let bad = compare(&inc, true);

    if !bad.is_empty() {
        return Err(format!(
            "assembly and crates/abi disagree on {} layout fact(s):\n{}\n\n\
             The .S files hardcode these numbers. Fix the include (or the record) \
             before anything links — a mismatch here corrupts exception entry and \
             context switching silently.",
            bad.len(),
            bad.join("\n")
        ));
    }

    println!("asm-defs OK: {REFERENCE_INC} agrees with crates/abi");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reads_a_plain_define() {
        let inc = "#define S_FRAME_SIZE            272\n";
        assert_eq!(literal(inc, "S_FRAME_SIZE"), Some(272));
    }

    #[test]
    fn reads_a_define_with_a_trailing_comment() {
        let inc = "#define NR_SYSCALLS  56 /* highest slot + 1 */\n";
        assert_eq!(literal(inc, "NR_SYSCALLS"), Some(56));
    }

    /// `PAGE_SHIFT` must not answer a lookup for `PAGE_S` — a prefix match would
    /// silently compare the wrong constant and report a false pass.
    #[test]
    fn does_not_prefix_match_a_longer_name() {
        let inc = "#define PAGE_SHIFT          12\n";
        assert_eq!(literal(inc, "PAGE_SH"), None);
    }

    /// Composed expressions are arch constants, not Rust-owned layout facts. The
    /// parser must decline them rather than guess.
    #[test]
    fn declines_a_composed_expression() {
        let inc = "#define PAGE_SIZE           (1 << PAGE_SHIFT)\n";
        assert_eq!(literal(inc, "PAGE_SIZE"), None);
    }

    #[test]
    fn missing_define_is_none() {
        assert_eq!(literal("#define OTHER 1\n", "S_FRAME_SIZE"), None);
    }

    /// The real include opens with a comment block and interleaves composed
    /// expressions and `.macro` bodies between the plain defines. A parser that
    /// gives up at the first non-`#define` line reports every fact as missing —
    /// which reads as "the assembly changed" instead of "the parser is broken".
    #[test]
    fn skips_non_define_lines_to_reach_a_later_define() {
        let inc = "\
/*
 * Common assembly-level constants.
 */
#define PAGE_SHIFT          12
#define PAGE_SIZE           (1 << PAGE_SHIFT)

/* ---- exception entry ---- */
#define S_FRAME_SIZE            272
";
        assert_eq!(literal(inc, "S_FRAME_SIZE"), Some(272));
        assert_eq!(literal(inc, "PAGE_SHIFT"), Some(12));
    }

    /// The live include must pass — this is the gate in its green state.
    #[test]
    fn the_real_include_agrees_with_the_abi_crate() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
        let inc = std::fs::read_to_string(root.join(REFERENCE_INC)).unwrap();
        assert!(
            compare(&inc, false).is_empty(),
            "arch/aarch64/asm_defs_common.inc drifted from crates/abi"
        );
    }

    /// A gate that cannot fail proves nothing: a stale frame size in the assembly
    /// must be reported, not shrugged off.
    #[test]
    fn a_stale_frame_size_in_the_assembly_is_caught() {
        let inc = "\
#define S_FRAME_SIZE            256
#define NR_SYSCALLS             56
#define CORE_CONTEXT_OFFSET     0
";
        let bad = compare(inc, false);
        assert_eq!(bad.len(), 1, "expected exactly one disagreement: {bad:?}");
        assert!(bad[0].contains("S_FRAME_SIZE"));
        assert!(bad[0].contains("assembly says 256"));
    }

    /// The other direction of the same trap: a syscall appended to the ABI crate
    /// without bumping the dispatch cap in the assembly.
    #[test]
    fn a_stale_syscall_cap_in_the_assembly_is_caught() {
        let inc = "\
#define S_FRAME_SIZE            272
#define NR_SYSCALLS             55
#define CORE_CONTEXT_OFFSET     0
";
        let bad = compare(inc, false);
        assert_eq!(bad.len(), 1);
        assert!(bad[0].contains("NR_SYSCALLS"));
    }

    /// The generated include must carry every fact, and each must be the value
    /// the record actually has — not a copy that can rot.
    #[test]
    fn rendered_include_carries_the_live_values() {
        let s = render();
        for f in facts() {
            assert!(
                s.contains(&format!("#define {:<20} {}", f.name, f.value)),
                "generated include is missing {}",
                f.name
            );
        }
        assert!(s.contains("272"), "S_FRAME_SIZE must render as 272");
        assert!(s.contains("56"), "NR_SYSCALLS must render as 56");
    }
}
